name: pg_worker
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  postgres: ^3.5.0
  uuid: ^4.5.1
  easy_cron: ^0.9.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
